title: CNC 
description: Manual para configuración y operación de la CNC con Arduino + GRBL

# ✅ Modo recomendado en GitHub Pages:
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

lang: es
url: "https://hubergiron.github.io/"
baseurl: "/cnc"

just_the_docs:
  # incluir CSS adicional
  custom_css:
    - "assets/css/custom.css"
  footer_content: ""

search_enabled: true
search:
  heading_level: 1

aux_links:
  "Repositorio en GitHub":
    - "https://github.com/HuberGiron/cnc"

# Enlaces
permalink: pretty

plugins:
  - jekyll-seo-tag

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor"
